### ISSUE TITLE
first submenu point gives an error

### ISSUE THREAD

**Issue by morange** [b13/menus#77]
If the first submenu item is called, the following error message is displayed:

Tue, 23 Aug 2022 13:00:40 +0000 [CRITICAL] request="2349ed0797b81" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: FE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key "prev" in /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php line 1063- Exception: PHP Warning: Undefined array key "prev" in /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php line 1063, in file /var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php:137 - {"mode":"WEB","application_mode":"FE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php","line":137,"message":"PHP Warning: Undefined array key \"prev\" in /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php line 1063","request_url":"https://tus-fresh.ddev.site/sparten/basketball.html","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"prev\" in /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php line 1063 in /var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php:137\nStack trace:\n#0 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php(1063): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/p...', 1063)\n#1 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php(544): TYPO3\\CMS\\Frontend\\ContentObject\\Menu\\AbstractMenuContentObject->prepareMenuItemsForBrowseMenu(515, 'sorting', ' AND pages.dokt...')\n#2 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php(383): TYPO3\\CMS\\Frontend\\ContentObject\\Menu\\AbstractMenuContentObject->prepareMenuItems()\n#3 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/HierarchicalMenuContentObject.php(56): TYPO3\\CMS\\Frontend\\ContentObject\\Menu\\AbstractMenuContentObject->makeMenu()\n#4 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(800): TYPO3\\CMS\\Frontend\\ContentObject\\HierarchicalMenuContentObject->render(Array)\n#5 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\HierarchicalMenuContentObject), Array)\n#6 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(1545): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('HMENU', Array, '/stdWrap/.cObje...')\n#7 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(1347): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->stdWrap_cObject('', Array)\n#8 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(1326): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->stdWrap('', Array)\n#9 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/HierarchicalMenuContentObject.php(65): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->stdWrap('', Array)\n#10 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(800): TYPO3\\CMS\\Frontend\\ContentObject\\HierarchicalMenuContentObject->render(Array)\n#11 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\HierarchicalMenuContentObject), Array)\n#12 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(698): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('HMENU', Array, '10')\n#13 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectArrayContentObject.php(43): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#14 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(800): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectArrayContentObject->render(Array)\n#15 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectArrayContentObject), Array)\n#16 /var/www/html/public/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php(197): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('COA', Array, 'lib.backbutton')\n#17 /var/www/html/public/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php(174): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper::renderContentObject(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer), Array, 'lib.backbutton', 'backbutton')\n#18 /var/www/html/var/cache/code/fluid_template/Standard_action_index_e6f867e69e1273801bb48a5ad14b5a05b04b0e65.php(186): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#19 /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(258): Standard_action_index_e6f867e69e1273801bb48a5ad14b5a05b04b0e65->section_186817d730a4234a5cb5db37d7099a3440fc5dea(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#20 /var/www/html/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(171): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('MainContent', Array, false)\n#21 /var/www/html/var/cache/code/fluid_template/layout_Default_html_f3a95b5ac0cd9e6ea25e910fd5a3c3bac0cea718.php(132): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#22 /var/www/html/vendor/typo3fluid/fluid/src/ViewHelpers/SpacelessViewHelper.php(61): layout_Default_html_f3a95b5ac0cd9e6ea25e910fd5a3c3bac0cea718->{closure}()\n#23 /var/www/html/var/cache/code/fluid_template/layout_Default_html_f3a95b5ac0cd9e6ea25e910fd5a3c3bac0cea718.php(267): TYPO3Fluid\\Fluid\\ViewHelpers\\SpacelessViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#24 /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(200): layout_Default_html_f3a95b5ac0cd9e6ea25e910fd5a3c3bac0cea718->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#25 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php(340): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#26 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php(106): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#27 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(800): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#28 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#29 /var/www/html/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(698): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, '10')\n#30 /var/www/html/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(223): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#31 /var/www/html/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(189): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageBodyContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))\n#32 /var/www/html/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(141): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController), Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /var/www/html/public/typo3/sysext/core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#34 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))\n#35 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/OutputCompression.php(48): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#36 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#37 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/ContentLengthResponseHeader.php(46): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#38 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#39 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(79): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#40 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#41 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#42 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#43 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(104): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#44 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#45 /var/www/html/public/typo3conf/ext/yoast_seo/Classes/Middleware/PageRequestMiddleware.php(32): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#46 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): YoastSeoForTypo3\\YoastSeo\\Middleware\\PageRequestMiddleware->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#47 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PageArgumentValidator.php(132): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#48 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#49 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php(66): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#50 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#51 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(106): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#52 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#53 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(80): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#54 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#55 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(94): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#56 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#57 /var/www/html/public/typo3/sysext/redirects/Classes/Http/Middleware/RedirectHandler.php(84): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#58 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#59 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(91): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#60 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#61 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#62 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#63 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#64 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#65 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#66 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#67 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(64): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#68 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#69 /var/www/html/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#70 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#71 /var/www/html/public/typo3/sysext/core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#72 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#73 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(58): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#74 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#75 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#76 /var/www/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(86): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#77 /var/www/html/public/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#78 /var/www/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(100): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#79 /var/www/html/public/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#80 /var/www/html/public/index.php(21): {closure}()\n#81 {main}"}

I'm using TYPO3 v11.5.14 and PHP 8.0 in an DDEV Project.

**Comment by bmack** [comment]
Hi @morange ,
this looks like a TYPO3 Core bug, as you are using AbstractMenuContentObject and not EXT:menus (did not find any occurrence of "B13/Menus" in your stack trace)

**Comment by morange** [comment]
Hi @bmack,
thank you for your feedback. where do we go from here?

**Comment by bmack** [comment]
Hi @morange ,

from looking at the stack trace this is a TYPO3 v11 bugfix in TYPO3 Core, solved yesterday by @o-ba in TYPO3 Core. The next TYPO3 v11.5.x maintenance release will contain the issue and resolve the issue https://review.typo3.org/c/Packages/TYPO3.CMS/+/75811

You can also downgrade to PHP 7.4 in your DDEV project today to see that the error is not related to EXT:menus but related to TYPO3 Core itself.

**Comment by morange** [comment]
Hej @bmack,
thanks for your quick reply and pointing out the fix.cool that it was already fixed in core. CLASS
I am currently working locally with PHP7.4 to continue. 
Many thanks
